//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackgroundCallLog
    {
        public int BackgroundCallLogId { get; set; }
        public System.DateTime BackgroundCallLogTime { get; set; }
        public string BackgroundCallLogMessage { get; set; }
    }
}
