//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAsset
    {
        public System.Guid GUID { get; set; }
        public string TargerEnvaironment { get; set; }
        public string DataField { get; set; }
        public decimal BucketId { get; set; }
    }
}
